version: "3.9"

networks:
  gochat_net:
    name: gochat_net
    driver: bridge

services:
  auth:
    container_name: gochat_auth
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    command: sh -c "
      ./migrate -path ./schema -database  postgres://postgres:postgres@db_auth:5432/auth?sslmode=disable up
      && ./main"
    networks:
      - gochat_net
    depends_on:
      - db_auth

  db_auth:
    container_name: gochat_auth_db
    image: postgres:16.2
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_NAME=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    networks:
      - gochat_net
    volumes:
      - auth_db:/var/lib/postgresql/data

volumes:
  auth_db:
